apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: react-user-picker
  title: React User Picker Component
  description: A template for creating a React User Picker component and publishing it to a new GitHub repository.
spec:
  owner: dipakmca09
  type: service

  parameters:
    - title: Component Details
      required:
        - componentName
        - userOptions
      properties:
        componentName:
          title: Component Name
          type: string
          description: The name of the React component (e.g., UserPicker).
          ui:autofocus: true

        userOptions:
          title: User Options
          type: string
          description: Enter comma-separated options for the User Picker component (e.g., "Alice,Bob,Charlie").
          ui:options:
            rows: 3

    - title: Repository Details
      required:
        - repoName
      properties:
        repoName:
          title: New Repository Name
          type: string
          description: The name of the new GitHub repository where the component will be published.

  steps:
    - id: fetch-template
      name: Fetch Template
      action: fetch:template
      input:
        url: https://github.com/dipakmca09/software-templates
        values:
          componentName: ${{ parameters.componentName }}
          userOptions: ${{ parameters.userOptions }}

    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: "A React User Picker component generated using Backstage."
        repoUrl: github.com?owner=dipakmca09&repo=${{ parameters.repoName }}
        defaultBranch: main
